### ISSUE TITLE
Place All items button can move Skulker Boxes into other Shulker Boxes

### ISSUE THREAD

**Issue by SleepyCanine** [Roundaround/mc-fabric-inventory-management#1]
When using the Place All button, the mod can force shulker boxes into other shulker boxes

Tested with Inventory Management v1.0.0 and Fabric API 0.55.3 on Minecraft 1.19, no other mods loaded

![image](https://user-images.githubusercontent.com/7709691/173415806-67f20b8b-0acb-414c-b3de-0fa2e4511205.png)
![image](https://user-images.githubusercontent.com/7709691/173416123-a99885f9-daab-4c80-85a2-c6dfffe18f1c.png)

**Comment by Roundaround** [comment]
Hah! Interesting. Guess I need to do some additional checks before transferring

**Comment by Roundaround** [comment]
@SleepyCanine fixed in 1.0.1! Thanks for reporting!

https://modrinth.com/mod/roundaround-inventory-management/version/1.0.1
