### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Roundaround/mc-fabric-inventory-management#11]

**Comment by Zorklis** [comment]
This is one of my must have mods and I need, hopefully it gets updated

**Comment by sternschnaube** [comment]
Sure @Zorklis 😊
Just give it some time.

**Comment by Roundaround** [comment]
Hey folks, sorry for the long delay! Lots of stuff happening. Updated to 1.19.3!

https://modrinth.com/mod/roundaround-inventory-management/version/1.1.0+1.19.3

**Comment by sternschnaube** [comment]
Awesome, thanks 🥳
