### ISSUE TITLE
GUI Themes don't work

### ISSUE THREAD

**Issue by Pectacular** [Roundaround/mc-fabric-inventory-management#16]
Auto GUI theme doesn't make my buttons dark even though I have VT dark UI enabled. Also, if I change the GUI theme to dark manually, when I restart my game the buttons are back to light

**Comment by Roundaround** [comment]
Thanks for reporting! Fixed in all three 1.19.x versions. Check out 1.1.2 for 1.19-1.19.2 or 1.19.3, or 1.2.2 for 1.19.4 on Modrinth!

https://modrinth.com/mod/inventory-management
