### ISSUE TITLE
[Suggestion] Expanded Storage support

### ISSUE THREAD

**Issue by crest1993** [Roundaround/mc-fabric-inventory-management#2]
Any chances it will support expanded storage?

**Comment by Roundaround** [comment]
I've built the ability to add custom mod containers to the list of supported ones for the mod, but it'll ultimately be up to the mod's author to make the integration. Generally any mods that extend vanilla containers will work automatically, but if they wrote completely custom code they would need to make the integration themselves. If there's a particular mod you want compatibility with, I'd suggest reaching out to its author (or open an issue in their tracking system). I'm happy to assist mod creators in creating the integration if they need any help.

**Comment by ModProg** [comment]
I would be interrested in implementing support for inmis backpacks, could you maybe provide some documentation on what would need to be implemented for that?
