### ISSUE TITLE
No Config file in 1.18.2 Fabric

### ISSUE THREAD

**Issue by Sentinaut** [Roundaround/mc-fabric-inventory-management#28]
On the mod page it says how there's a config file called 'inventorymanagement.toml' but there is not.
I tried creating one to see if it would populate the file, but it stills its in the config folder at 0kb in size.

There is also no config button in Mod Menu
![image](https://github.com/Roundaround/mc-fabric-inventory-management/assets/161860536/e67af8e6-9c39-4c04-acc6-9480e21b62bb)

**Comment by Roundaround** [comment]
The config file wasn't added until v1.1.0 for 1.19. Unfortunately the configuration library I wrote and use wasn't ready for the 1.18.2 version. I've added a little blurb about it on the mod's description page. Sorry for the confusion!

**Comment by Sentinaut** [comment]
> The config file wasn't added until v1.1.0 for 1.19. Unfortunately the configuration library I wrote and use wasn't ready for the 1.18.2 version. I've added a little blurb about it on the mod's description page. Sorry for the confusion!

Aw man, that's alright - no problem. Thanks
