### ISSUE TITLE
Mod doesn't load on server

### ISSUE THREAD

**Issue by mrniddala** [Roundaround/mc-fabric-inventory-management#3]
Hello, I put the mod into my mods folder but the server doesn't load it.

Here is my server log (if it helps)
https://pastebin.com/raw/ExPg8FA0

Thanks already!

**Comment by Roundaround** [comment]
Whoops, fixed in 1.0.2. Sorry for the delay!

https://modrinth.com/mod/roundaround-inventory-management/version/1.0.2

**Comment by mrniddala** [comment]
Thank you a lot - keep up the great work, awesome mod(s) 🥰
