### ISSUE TITLE
Mod doesn't work ):

### ISSUE THREAD

**Issue by Mangareaderrr** [Roundaround/mc-fabric-inventory-management#33]
So whenever I attempt to use this mod, the buttons seem to not work when I click them. I'm not too sure what the issue could be. D:

**Comment by Roundaround** [comment]
This could be any number of things, but I'd need more information to figure it out:

- What Minecraft version are you playing?
- What mod loader are you using (Fabric, Quilt, etc)?
- What other mods do you have installed?
- Are you playing on a server? And if so, have you installed the mod on both your client _and_ the server?

**Comment by Mangareaderrr** [comment]
So, I'm playing on version 1.20.4!

I'm using Fabric (feather client).

I have several other mods installed, I'll list them here: 
- Xaero's Minimap
- Roughly Enough Items (REI)
- Roughly Searchable
- Roughly enough professions (rep)
- Mod Menu
- Sodium
- YetAnotherConfigLib
- ImmediatelyFast
- Entity Culling
- Cloth Config API
- Architectury API
- Inventory Management (Your mod)

I'm playing on a realm, so I'm not too sure if I'd be able to install in on the realm aswell.

**Comment by Roundaround** [comment]
Ah so the mod needs to be installed on the server. In your case that would be the realm (which is unfortunately not possible).

While it's technically possible to make this work completely client-side, it's not something I want to maintain or be responsible for. In Minecraft, your inventory is tracked completely server side and your local game is basically just told what is there. Trying to get around this with a bunch of manual actions is slow and error prone, and can even get caught by some anti-cheats.

Sorry I don't have better news for you!
